### PR TITLE
fix: #845 deprecated argument of tldr

### PR DESCRIPTION
**Pull request by dynamotn**
Related MR of `tldr`: https://github.com/dbrgn/tealdeer/pull/290

### CODE REVIEW

**Comment by jackandroselv** [comment]
您好！您的邮件我已收到，我会尽快的查阅邮件。谢谢您的来信！

**Comment by phanirithvij** [comment]
```shell
⋊> ~ tldr --raw
usage: tldr command [options]
tldr: error: unrecognized arguments: --raw
```
Doesn't work with anything other than tealdeer. See https://github.com/dbrgn/tealdeer/issues/321

**Comment by denisidoro** [comment]
Can you adjust the PR to ensure it works with tealdeer but also with the npm version of tldr? Thanks!

**Comment by Jamarcussw1** [comment]
Nice

**Pull request closed without merging**
