### PR TITLE
Trigger edit on the current cheat file

### LINKED ISSUE #357: Triggering edit on the current cheat file.
Hi!

Is it possible to implement a way to trigger own editor on the current or even just a certain navi cheat file based on a keybinding?

Now feels quite cumbersome that it needs to separately navigate to those files before editing.

### PR DESCRIPTION
**Pull request by b3s1r**
The currently selected item can now be opened with ctrl-o in the standard editor defined by VISUAL or EDITOR.
fixes #357

### CODE REVIEW

**Comment by denisidoro** [comment]
Cool! Thanks!

But I was wondering if we could have a cheaper solution: instead of appending the filepath to each line, we could append an index only and, when hitting Ctrl-O, we could match that with an array/map to get the filepath back. 

Please let me know if you intend to work in such an implementation. If not, I can merge it as-is and work on it later.

**Comment by b3s1r** [comment]
Yeah, good idea!
I'll have a think about it and try to implement in the next few days.

**Comment by denisidoro** [comment]
Thanks!

However, this way the `files` vec will contain a lot of repeated filepaths, right? We could reuse indices.

I'll merge it as-is and try to change this bit tomorrow.

**Comment by denisidoro** [comment]
By the way, it won't work as expected if the snippet has a variable. I'll fix it as well.

**Pull request merged**
