### PR TITLE
#60 names can include dashes or spaces

### PR DESCRIPTION
**Pull request by engrravijain**
The variable names can now include dashes or spaces in the cheatsheets.

### CODE REVIEW

**Comment by engrravijain** [comment]
Hey @denisidoro, I am able to pass all test cases on my local system. please check once.

**Comment by denisidoro** [comment]
Are you on OSX? I believe your changes won't work with GNU utils

**Comment by denisidoro** [comment]
You can run your tests in a local container by running scripts/docker then /navi/test/run

**Comment by engrravijain** [comment]
No, I am not on OS X. I'll try running it in docker. Thanks. :)

**Pull request merged**
