### PR TITLE
Use 2+ spaces as column separator

### LINKED ISSUE #153: Select columns, counting from the right
Due to some outputs being unreliable or with potential for spaces in the value, is it possible to support selection of columns, counting from the right? 

NAME      | VALUE
------------ | -------------
hello         | world
foo bar | baz

As in this example, providing `--- --column 2` would incorrectly fetch "bar" instead of "baz" in the second row.

### PR DESCRIPTION
**Pull request by denisidoro**
Fixes #153

### CODE REVIEW

**Comment by spoki0** [comment]
Does this by default use 2 spaces, or does it require `--separator 2` or `--separator '\s\s+'` as parameter? I am not able to get it working either way.

Do I need to do anything in particular to restart the plugin if I switch branches?

**Comment by denisidoro** [comment]
It doesn't require any additional configs.

--separator foo should work, though

You just need to change the branch:

cd "$(navi home)" 
git pull
git checkout column/sep

**Comment by denisidoro** [comment]
It doesn't require any additional configs.

--separator foo should work, though

You just need to change the branch:

cd "$(navi home)" 
git pull
git checkout column/sep

**Comment by spoki0** [comment]
I'm getting an error in a previous step of the command now :(

`awk: not an option: --{print $1}`

**Comment by denisidoro** [comment]
There was a typo 🤦‍♂ 

Could you git pull and try again please?

**Comment by spoki0** [comment]
Typos happen to everyone.
Anyways, that seems to work perfectly by default for my the few command cheats I have written. It doesn't split the row where the value have a space, so it is much better.

Testing the `--separator` out, but I'm not sure it works as expected with whitespace values. I keep getting the `unable to fetch suggestions for 'value'!` when trying to use ex. `--separator ' '`. But splitting on an arbitrary symbol otherwise worked without issue.

**Comment by denisidoro** [comment]
I'll merge it as-is and fix this particular issue in another PR. Thanks!

**Pull request merged**
